const fs = require('fs');
const pl = JSON.parse(fs.readFileSync('src/locales/pl/translation.json', 'utf8'));

Object.assign(pl, {
  "auto.trening": "Trening",
  "auto.ustawienia": "Ustawienia",
  "auto.ustawienia_aplikacji": "Ustawienia aplikacji",
  "auto.nawyki": "Nawyki",
  "auto.przypomnienia": "Przypomnienia",
  "auto.api_i_chmura": "API & Chmura",
  "auto.silownia_trening_silowy": "Siłownia (Trening Siłowy)",
  "auto.wplyw_sportu": "Wpływ sportu",
  "auto.wiedza": "Wiedza",
  "auto.historia": "Historia",
  "auto.wybierz_dyscypline": "Wybierz dyscyplinę",
  "auto.wybierz_dyscyplinę": "Wybierz dyscyplinę",
  "auto.dodaj_trening": "Dodaj Trening",
  "auto.zapisz_trening": "Zapisz Trening",
  "auto.rozmaite_wysilki_fizyczne": "Rozmaite wysiłki fizyczne mają różny wpływ na poziom glukozy. Wybierz dyscyplinę, aby dowiedzieć się na co uważać.",
  "auto.rozmaite_wysiłki_fizyczne_mają_różn": "Rozmaite wysiłki fizyczne mają różny wpływ na poziom glukozy. Wybierz dyscyplinę, aby dowiedzieć się na co uważać.",
  "auto.silownia": "Siłownia",
  "auto.czesto_podnosi_poziom_cukru": "Często podnosi poziom cukru",
  "auto.czesto_podnosi_poziom_cuk": "Często podnosi poziom cukru",
  "auto.krotki_intensywny_wysilek_uwal": "Krótki, intensywny wysiłek uwalnia adrenalinę, która stymuluje wątrobę do wyrzutu glukozy. Często powoduje niespodziewane wzrosty glikemii w trakcie i po treningu.",
  "auto.krotki_intensywny_wysilek": "Krótki, intensywny wysiłek uwalnia adrenalinę, która stymuluje wątrobę do wyrzutu glukozy. Często powoduje niespodziewane wzrosty glikemii w trakcie i po treningu.",
  "auto.mozesz_potrzebowac_malego_bolu": "Możesz potrzebować małego bolusa przed siłownią.",
  "auto.mozesz_potrzebowac_malego": "Możesz potrzebować małego bolusa przed siłownią.",
  "auto.intensywnosc": "Intensywność",
  "auto.niska": "Niska",
  "auto.srednia": "Średnia",
  "auto.wysoka": "Wysoka",
  "auto.czas_trwania_min": "Czas trwania (min)",
  "auto.dodaj_do_dziennika": "Dodaj do Dziennika",
  "auto.trening_dodany": "Trening dodany",
  "auto.taniec": "Taniec",
  "auto.joga": "Joga",
  "auto.marsz_spacer": "Marsz / Spacer",
  "auto.bieganie_kardio": "Bieganie / Kardio",
  "auto.rower": "Rower",
  "auto.plywanie": "Pływanie",
  "auto.czesto_obniza_poziom_cukru": "Często obniża poziom cukru",
  "auto.umiarkowany_dlugotrwaly_wysi": "Umiarkowany, długotrwały wysiłek spala glukozę miarowo.",
  "auto.nieprzewidywalny_wplyw_za": "Nieprzewidywalny wpływ w zależności od intensywności.",
  "auto.szybkie_wpisy": "Szybkie Wpisy",
  "auto.faq_pomoc": "FAQ & Pomoc",
  "auto.faq_i_pomoc": "FAQ & Pomoc",
  "auto.symulator_bolusa": "Symulator Bolusa",
  "auto.symulator": "Symulator",
  "auto.marsz": "Marsz",
  "auto.szybkie_wpisy_skroty": "Szybkie Wpisy",
  "auto.bardzo_szybko_obniza_poziom": "Bardzo szybko obniża poziom cukru",
  "auto.moze_powodowac_hipoglikemie": "Może powodować opóźnioną hipoglikemię. Przygotuj węglowodany.",
  "auto.zwykle_lagodnie_obniza_poz": "Zwykle łagodnie obniża poziom cukru",
  "auto.pomaga_zwiekszyc_wrazliwosc": "Pomaga zwiększyć wrażliwość na insulinę w czasie.",
  "auto.intensywny_taniec_moze_z": "Intensywny taniec może działać jak kardio.",
  "auto.opozniona_hipoglikemia_je": "Opóźniona hipoglikemia jest bardzo częsta nawet do 24h po.",
  "auto.czesto_zwieksza_wrazliwo": "Często zwiększa wrażliwość i obniża cukier miarowo."
});

fs.writeFileSync('src/locales/pl/translation.json', JSON.stringify(pl, null, 2));
